#!/usr/bin/env bash
set -euo pipefail

DIR="$(pwd)"

function display_help {
  echo "./$(basename "$0") [ -d | --directory DIRECTORY ] [ -h | --help ]
Script to validate the manifests generated by Helm
Where:
  -d  | --directory DIRECTORY  Base directory containing Helm charts
  -h  | --help                 Display this help text"
}

if ! command -v "helm" >/dev/null; then
    echo "helm command not available."
    exit 1
fi

echo "Helm version:"
helm version

HELM_CMD="helm lint"
HELM_DIR="${DIR}"

for i in "$@"
do
  case $i in
    -d=* | --directory=* )
      HELM_DIR="${i#*=}"
      shift
      ;;
    -h | --help )
      display_help
      exit 0
      ;;
  esac
done

HELM_CHARTS=$(find "${HELM_DIR}" -type f -name "Chart.yaml" -exec dirname {} +)

echo "Helm charts:"
echo "${HELM_CHARTS}"

for i in ${HELM_CHARTS}; do

    echo
    echo "Pulling dependencies for $i"
    helm dependency build "$i"
    echo

    $HELM_CMD "$i"

    if ! $HELM_CMD "$i"; then
        echo "Error linting chart $i"
        exit 1
    fi

done

echo
echo "Charts successfully validated!"
