#!/usr/bin/env bash
set -euo pipefail

DIR="$(pwd)"

function display_help {
    echo "./$(basename "$0") [ -d | --directory DIRECTORY ] [ -h | --help ]
Script to validate the manifests generated by Helm
Where:
  -d  | --directory DIRECTORY  Base directory containing Helm charts
  -h  | --help                 Display this help text"
}

if ! command -v "helm" >/dev/null; then
    echo "helm command not available."
    exit 1
fi

echo "Helm version: $(helm version)"
echo

HELM_DIR="${DIR}"

for i in "$@"
do
  case $i in
    -d=* | --directory=* )
      HELM_DIR="${i#*=}"
      shift
      ;;
    -h | --help )
      display_help
      exit 0
      ;;
  esac
done

HELM_CHARTS=$(find "${HELM_DIR}" -type f -name "Chart.yaml" -exec dirname {} +)

echo "Helm charts found:"
echo "${HELM_CHARTS}"
echo

for i in ${HELM_CHARTS}; do

    dep_output=$(helm dependency list "$i" 2>&1)
    dep_status=$?

    if [ $dep_status -ne 0 ]; then
        echo "Error listing dependencies for chart $i:"
        echo "$dep_output"
        exit 1
    fi

    helm_repos=$(helm repo list 2>/dev/null || true)
    dep_output=$(echo "$dep_output" | grep -v "NAME\|WARNING" || true)

    if [ -n "$dep_output" ]; then
        echo "$dep_output" | awk 'NF > 0 { print $1, $3 }' | while read -r repo_name repo_url; do
            if ! echo "$helm_repos" | grep -q "$repo_url"; then
                echo "Adding repo: $repo_name $repo_url"
                helm repo add "$repo_name" "$repo_url"
            fi
        done
    fi

    echo
    echo "Pulling dependencies for $i"
    helm dependency build "$i"
    echo

    helm dependency build "$i"

    if ! helm lint "$i"; then
        echo "Error linting chart $i"
        exit 1
    fi

done

echo
echo "Charts successfully validated!"
